version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_server
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer:4.8.1
    container_name: adminer_ui
    restart: always
    ports:
      - "7080:8080"

volumes:
  postgres_data: